#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fron_End
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDBecasUAC")]
	public partial class BDBecasUACDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTUsuario(TUsuario instance);
    partial void UpdateTUsuario(TUsuario instance);
    partial void DeleteTUsuario(TUsuario instance);
    partial void InsertTEscuela(TEscuela instance);
    partial void UpdateTEscuela(TEscuela instance);
    partial void DeleteTEscuela(TEscuela instance);
    partial void InsertTModalidadBeca(TModalidadBeca instance);
    partial void UpdateTModalidadBeca(TModalidadBeca instance);
    partial void DeleteTModalidadBeca(TModalidadBeca instance);
    partial void InsertTObservacion(TObservacion instance);
    partial void UpdateTObservacion(TObservacion instance);
    partial void DeleteTObservacion(TObservacion instance);
    partial void InsertTRequisitosBeca(TRequisitosBeca instance);
    partial void UpdateTRequisitosBeca(TRequisitosBeca instance);
    partial void DeleteTRequisitosBeca(TRequisitosBeca instance);
    partial void InsertTSolicitudBeca(TSolicitudBeca instance);
    partial void UpdateTSolicitudBeca(TSolicitudBeca instance);
    partial void DeleteTSolicitudBeca(TSolicitudBeca instance);
    partial void InsertTDocumentoEntregado(TDocumentoEntregado instance);
    partial void UpdateTDocumentoEntregado(TDocumentoEntregado instance);
    partial void DeleteTDocumentoEntregado(TDocumentoEntregado instance);
    partial void InsertTDocumentoRequisito(TDocumentoRequisito instance);
    partial void UpdateTDocumentoRequisito(TDocumentoRequisito instance);
    partial void DeleteTDocumentoRequisito(TDocumentoRequisito instance);
    #endregion
		
		public BDBecasUACDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BDBecasUACConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDBecasUACDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDBecasUACDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDBecasUACDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDBecasUACDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TUsuario> TUsuario
		{
			get
			{
				return this.GetTable<TUsuario>();
			}
		}
		
		public System.Data.Linq.Table<TEncargado_BU> TEncargado_BU
		{
			get
			{
				return this.GetTable<TEncargado_BU>();
			}
		}
		
		public System.Data.Linq.Table<TEscuela> TEscuela
		{
			get
			{
				return this.GetTable<TEscuela>();
			}
		}
		
		public System.Data.Linq.Table<TEstudiante> TEstudiante
		{
			get
			{
				return this.GetTable<TEstudiante>();
			}
		}
		
		public System.Data.Linq.Table<TModalidadBeca> TModalidadBeca
		{
			get
			{
				return this.GetTable<TModalidadBeca>();
			}
		}
		
		public System.Data.Linq.Table<TObservacion> TObservacion
		{
			get
			{
				return this.GetTable<TObservacion>();
			}
		}
		
		public System.Data.Linq.Table<TRequisitosBeca> TRequisitosBeca
		{
			get
			{
				return this.GetTable<TRequisitosBeca>();
			}
		}
		
		public System.Data.Linq.Table<TSolicitudBeca> TSolicitudBeca
		{
			get
			{
				return this.GetTable<TSolicitudBeca>();
			}
		}
		
		public System.Data.Linq.Table<TDocumentoEntregado> TDocumentoEntregado
		{
			get
			{
				return this.GetTable<TDocumentoEntregado>();
			}
		}
		
		public System.Data.Linq.Table<TDocumentoRequisito> TDocumentoRequisito
		{
			get
			{
				return this.GetTable<TDocumentoRequisito>();
			}
		}
		
		public System.Data.Linq.Table<vistaSolicitudesPorModalidad> vistaSolicitudesPorModalidad
		{
			get
			{
				return this.GetTable<vistaSolicitudesPorModalidad>();
			}
		}
		
		public System.Data.Linq.Table<vistaSolicitudesPorEscuela> vistaSolicitudesPorEscuela
		{
			get
			{
				return this.GetTable<vistaSolicitudesPorEscuela>();
			}
		}
		
		public System.Data.Linq.Table<vistaSolicitudesPorEstado> vistaSolicitudesPorEstado
		{
			get
			{
				return this.GetTable<vistaSolicitudesPorEstado>();
			}
		}
		
		public System.Data.Linq.Table<vistaSolicitudesAprobadasPorEscuela> vistaSolicitudesAprobadasPorEscuela
		{
			get
			{
				return this.GetTable<vistaSolicitudesAprobadasPorEscuela>();
			}
		}
		
		public System.Data.Linq.Table<vistaSolicitudesAprobadasPorModalidad> vistaSolicitudesAprobadasPorModalidad
		{
			get
			{
				return this.GetTable<vistaSolicitudesAprobadasPorModalidad>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spLoginUsuario")]
		public ISingleResult<spLoginUsuarioResult> spLoginUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(50)")] string contrasena)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correo, contrasena);
			return ((ISingleResult<spLoginUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarEncargado")]
		public ISingleResult<spAgregarEncargadoResult> spAgregarEncargado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombres", DbType="VarChar(50)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="VarChar(50)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Celular", DbType="VarChar(9)")] string celular, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipDocumento", DbType="VarChar(1)")] string tipDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumDocIdentidad", DbType="VarChar(15)")] string numDocIdentidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(50)")] string contrasena)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correo, nombres, apellidos, celular, direccion, tipDocumento, numDocIdentidad, contrasena);
			return ((ISingleResult<spAgregarEncargadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spModificarUsuario")]
		public ISingleResult<spModificarUsuarioResult> spModificarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Char(5)")] string idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombres", DbType="VarChar(50)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="VarChar(50)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumDocIdentidad", DbType="VarChar(15)")] string numDocIdentidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Celular", DbType="VarChar(9)")] string celular, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string urlImagen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, nombres, apellidos, numDocIdentidad, direccion, celular, correo, urlImagen);
			return ((ISingleResult<spModificarUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarImagen")]
		public ISingleResult<spAgregarImagenResult> spAgregarImagen([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Char(5)")] string idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string urlImagen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, urlImagen);
			return ((ISingleResult<spAgregarImagenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListarRequisitoporModalidad")]
		public ISingleResult<spListarRequisitoporModalidadResult> spListarRequisitoporModalidad([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdModalidad", DbType="Char(5)")] string idModalidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idModalidad);
			return ((ISingleResult<spListarRequisitoporModalidadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarDocumentoEntregado")]
		public ISingleResult<spAgregarDocumentoEntregadoResult> spAgregarDocumentoEntregado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string enlace, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdSolicitud", DbType="Char(5)")] string idSolicitud, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(5)")] string idRequisitos)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), enlace, idSolicitud, idRequisitos);
			return ((ISingleResult<spAgregarDocumentoEntregadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListarDocumentosPorSolicitud")]
		public ISingleResult<spListarDocumentosPorSolicitudResult> spListarDocumentosPorSolicitud([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdSolicitud", DbType="Char(5)")] string idSolicitud)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idSolicitud);
			return ((ISingleResult<spListarDocumentosPorSolicitudResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarSolicitud")]
		public ISingleResult<spAgregarSolicitudResult> spAgregarSolicitud([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="VarChar(5)")] string idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdModalidadBeca", DbType="Char(5)")] string idModalidadBeca)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, idModalidadBeca);
			return ((ISingleResult<spAgregarSolicitudResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarObservacion")]
		public ISingleResult<spAgregarObservacionResult> spAgregarObservacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDocumentoEntregado", DbType="VarChar(5)")] string idDocumentoEntregado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(200)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDocumentoEntregado, descripcion);
			return ((ISingleResult<spAgregarObservacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spListarDocumentosPorUsuario")]
		public ISingleResult<spListarDocumentosPorUsuarioResult> spListarDocumentosPorUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Char(5)")] string idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((ISingleResult<spListarDocumentosPorUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAgregarEstudiante")]
		public ISingleResult<spAgregarEstudianteResult> spAgregarEstudiante([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombres", DbType="VarChar(50)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="VarChar(50)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Celular", DbType="VarChar(9)")] string celular, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipDocumento", DbType="VarChar(1)")] string tipDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumDocIdentidad", DbType="VarChar(15)")] string numDocIdentidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasena", DbType="VarChar(50)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEscuela", DbType="Char(4)")] string idEscuela)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correo, nombres, apellidos, celular, direccion, tipDocumento, numDocIdentidad, contrasena, idEscuela);
			return ((ISingleResult<spAgregarEstudianteResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUsuario")]
	public partial class TUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdUsuario;
		
		private string _Correo;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private string _Celular;
		
		private string _Direccion;
		
		private string _TipDocumento;
		
		private string _NumDocIdentidad;
		
		private string _Contrasena;
		
		private string _estado;
		
		private string _urlImagen;
		
		private EntitySet<TSolicitudBeca> _TSolicitudBeca;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(string value);
    partial void OnIdUsuarioChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTipDocumentoChanging(string value);
    partial void OnTipDocumentoChanged();
    partial void OnNumDocIdentidadChanging(string value);
    partial void OnNumDocIdentidadChanged();
    partial void OnContrasenaChanging(string value);
    partial void OnContrasenaChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OnurlImagenChanging(string value);
    partial void OnurlImagenChanged();
    #endregion
		
		public TUsuario()
		{
			this._TSolicitudBeca = new EntitySet<TSolicitudBeca>(new Action<TSolicitudBeca>(this.attach_TSolicitudBeca), new Action<TSolicitudBeca>(this.detach_TSolicitudBeca));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipDocumento", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string TipDocumento
		{
			get
			{
				return this._TipDocumento;
			}
			set
			{
				if ((this._TipDocumento != value))
				{
					this.OnTipDocumentoChanging(value);
					this.SendPropertyChanging();
					this._TipDocumento = value;
					this.SendPropertyChanged("TipDocumento");
					this.OnTipDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumDocIdentidad", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string NumDocIdentidad
		{
			get
			{
				return this._NumDocIdentidad;
			}
			set
			{
				if ((this._NumDocIdentidad != value))
				{
					this.OnNumDocIdentidadChanging(value);
					this.SendPropertyChanging();
					this._NumDocIdentidad = value;
					this.SendPropertyChanged("NumDocIdentidad");
					this.OnNumDocIdentidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(10)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlImagen", DbType="NVarChar(255)")]
		public string urlImagen
		{
			get
			{
				return this._urlImagen;
			}
			set
			{
				if ((this._urlImagen != value))
				{
					this.OnurlImagenChanging(value);
					this.SendPropertyChanging();
					this._urlImagen = value;
					this.SendPropertyChanged("urlImagen");
					this.OnurlImagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TSolicitudBeca", Storage="_TSolicitudBeca", ThisKey="IdUsuario", OtherKey="IdUsuario")]
		public EntitySet<TSolicitudBeca> TSolicitudBeca
		{
			get
			{
				return this._TSolicitudBeca;
			}
			set
			{
				this._TSolicitudBeca.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TSolicitudBeca(TSolicitudBeca entity)
		{
			this.SendPropertyChanging();
			entity.TUsuario = this;
		}
		
		private void detach_TSolicitudBeca(TSolicitudBeca entity)
		{
			this.SendPropertyChanging();
			entity.TUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TEncargado_BU")]
	public partial class TEncargado_BU
	{
		
		private string _IdUsuario;
		
		public TEncargado_BU()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TEscuela")]
	public partial class TEscuela : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdEscuela;
		
		private string _Nombre;
		
		private int _Num_Estudiante;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEscuelaChanging(string value);
    partial void OnIdEscuelaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnNum_EstudianteChanging(int value);
    partial void OnNum_EstudianteChanged();
    #endregion
		
		public TEscuela()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEscuela", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdEscuela
		{
			get
			{
				return this._IdEscuela;
			}
			set
			{
				if ((this._IdEscuela != value))
				{
					this.OnIdEscuelaChanging(value);
					this.SendPropertyChanging();
					this._IdEscuela = value;
					this.SendPropertyChanged("IdEscuela");
					this.OnIdEscuelaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Estudiante", DbType="Int NOT NULL")]
		public int Num_Estudiante
		{
			get
			{
				return this._Num_Estudiante;
			}
			set
			{
				if ((this._Num_Estudiante != value))
				{
					this.OnNum_EstudianteChanging(value);
					this.SendPropertyChanging();
					this._Num_Estudiante = value;
					this.SendPropertyChanged("Num_Estudiante");
					this.OnNum_EstudianteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TEstudiante")]
	public partial class TEstudiante
	{
		
		private string _IdUsuario;
		
		private string _IdEscuela;
		
		public TEstudiante()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEscuela", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string IdEscuela
		{
			get
			{
				return this._IdEscuela;
			}
			set
			{
				if ((this._IdEscuela != value))
				{
					this._IdEscuela = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TModalidadBeca")]
	public partial class TModalidadBeca : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdModalidadBeca;
		
		private string _Nombre_Modalidad;
		
		private System.Nullable<double> _Porcentaje_por_escuela;
		
		private EntitySet<TRequisitosBeca> _TRequisitosBeca;
		
		private EntitySet<TSolicitudBeca> _TSolicitudBeca;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdModalidadBecaChanging(string value);
    partial void OnIdModalidadBecaChanged();
    partial void OnNombre_ModalidadChanging(string value);
    partial void OnNombre_ModalidadChanged();
    partial void OnPorcentaje_por_escuelaChanging(System.Nullable<double> value);
    partial void OnPorcentaje_por_escuelaChanged();
    #endregion
		
		public TModalidadBeca()
		{
			this._TRequisitosBeca = new EntitySet<TRequisitosBeca>(new Action<TRequisitosBeca>(this.attach_TRequisitosBeca), new Action<TRequisitosBeca>(this.detach_TRequisitosBeca));
			this._TSolicitudBeca = new EntitySet<TSolicitudBeca>(new Action<TSolicitudBeca>(this.attach_TSolicitudBeca), new Action<TSolicitudBeca>(this.detach_TSolicitudBeca));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdModalidadBeca", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdModalidadBeca
		{
			get
			{
				return this._IdModalidadBeca;
			}
			set
			{
				if ((this._IdModalidadBeca != value))
				{
					this.OnIdModalidadBecaChanging(value);
					this.SendPropertyChanging();
					this._IdModalidadBeca = value;
					this.SendPropertyChanged("IdModalidadBeca");
					this.OnIdModalidadBecaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Modalidad", DbType="VarChar(55) NOT NULL", CanBeNull=false)]
		public string Nombre_Modalidad
		{
			get
			{
				return this._Nombre_Modalidad;
			}
			set
			{
				if ((this._Nombre_Modalidad != value))
				{
					this.OnNombre_ModalidadChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Modalidad = value;
					this.SendPropertyChanged("Nombre_Modalidad");
					this.OnNombre_ModalidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Porcentaje_por_escuela", DbType="Float")]
		public System.Nullable<double> Porcentaje_por_escuela
		{
			get
			{
				return this._Porcentaje_por_escuela;
			}
			set
			{
				if ((this._Porcentaje_por_escuela != value))
				{
					this.OnPorcentaje_por_escuelaChanging(value);
					this.SendPropertyChanging();
					this._Porcentaje_por_escuela = value;
					this.SendPropertyChanged("Porcentaje_por_escuela");
					this.OnPorcentaje_por_escuelaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TModalidadBeca_TRequisitosBeca", Storage="_TRequisitosBeca", ThisKey="IdModalidadBeca", OtherKey="IdModalidadBeca")]
		public EntitySet<TRequisitosBeca> TRequisitosBeca
		{
			get
			{
				return this._TRequisitosBeca;
			}
			set
			{
				this._TRequisitosBeca.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TModalidadBeca_TSolicitudBeca", Storage="_TSolicitudBeca", ThisKey="IdModalidadBeca", OtherKey="IdModalidadBeca")]
		public EntitySet<TSolicitudBeca> TSolicitudBeca
		{
			get
			{
				return this._TSolicitudBeca;
			}
			set
			{
				this._TSolicitudBeca.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TRequisitosBeca(TRequisitosBeca entity)
		{
			this.SendPropertyChanging();
			entity.TModalidadBeca = this;
		}
		
		private void detach_TRequisitosBeca(TRequisitosBeca entity)
		{
			this.SendPropertyChanging();
			entity.TModalidadBeca = null;
		}
		
		private void attach_TSolicitudBeca(TSolicitudBeca entity)
		{
			this.SendPropertyChanging();
			entity.TModalidadBeca = this;
		}
		
		private void detach_TSolicitudBeca(TSolicitudBeca entity)
		{
			this.SendPropertyChanging();
			entity.TModalidadBeca = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TObservacion")]
	public partial class TObservacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idObservacion;
		
		private string _idDocumentoEntregado;
		
		private string _Descripcion;
		
		private System.Nullable<System.DateTime> _FechaObservacion;
		
		private EntityRef<TDocumentoEntregado> _TDocumentoEntregado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidObservacionChanging(string value);
    partial void OnidObservacionChanged();
    partial void OnidDocumentoEntregadoChanging(string value);
    partial void OnidDocumentoEntregadoChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnFechaObservacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaObservacionChanged();
    #endregion
		
		public TObservacion()
		{
			this._TDocumentoEntregado = default(EntityRef<TDocumentoEntregado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idObservacion", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idObservacion
		{
			get
			{
				return this._idObservacion;
			}
			set
			{
				if ((this._idObservacion != value))
				{
					this.OnidObservacionChanging(value);
					this.SendPropertyChanging();
					this._idObservacion = value;
					this.SendPropertyChanged("idObservacion");
					this.OnidObservacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDocumentoEntregado", DbType="Char(5)")]
		public string idDocumentoEntregado
		{
			get
			{
				return this._idDocumentoEntregado;
			}
			set
			{
				if ((this._idDocumentoEntregado != value))
				{
					if (this._TDocumentoEntregado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDocumentoEntregadoChanging(value);
					this.SendPropertyChanging();
					this._idDocumentoEntregado = value;
					this.SendPropertyChanged("idDocumentoEntregado");
					this.OnidDocumentoEntregadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(200)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaObservacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaObservacion
		{
			get
			{
				return this._FechaObservacion;
			}
			set
			{
				if ((this._FechaObservacion != value))
				{
					this.OnFechaObservacionChanging(value);
					this.SendPropertyChanging();
					this._FechaObservacion = value;
					this.SendPropertyChanged("FechaObservacion");
					this.OnFechaObservacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TDocumentoEntregado_TObservacion", Storage="_TDocumentoEntregado", ThisKey="idDocumentoEntregado", OtherKey="idDocumentoEntregado", IsForeignKey=true)]
		public TDocumentoEntregado TDocumentoEntregado
		{
			get
			{
				return this._TDocumentoEntregado.Entity;
			}
			set
			{
				TDocumentoEntregado previousValue = this._TDocumentoEntregado.Entity;
				if (((previousValue != value) 
							|| (this._TDocumentoEntregado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TDocumentoEntregado.Entity = null;
						previousValue.TObservacion.Remove(this);
					}
					this._TDocumentoEntregado.Entity = value;
					if ((value != null))
					{
						value.TObservacion.Add(this);
						this._idDocumentoEntregado = value.idDocumentoEntregado;
					}
					else
					{
						this._idDocumentoEntregado = default(string);
					}
					this.SendPropertyChanged("TDocumentoEntregado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRequisitosBeca")]
	public partial class TRequisitosBeca : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idRequisitos;
		
		private string _IdModalidadBeca;
		
		private string _idDocumentoRequisito;
		
		private string _opcional;
		
		private EntitySet<TDocumentoEntregado> _TDocumentoEntregado;
		
		private EntityRef<TModalidadBeca> _TModalidadBeca;
		
		private EntityRef<TDocumentoRequisito> _TDocumentoRequisito;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRequisitosChanging(string value);
    partial void OnidRequisitosChanged();
    partial void OnIdModalidadBecaChanging(string value);
    partial void OnIdModalidadBecaChanged();
    partial void OnidDocumentoRequisitoChanging(string value);
    partial void OnidDocumentoRequisitoChanged();
    partial void OnopcionalChanging(string value);
    partial void OnopcionalChanged();
    #endregion
		
		public TRequisitosBeca()
		{
			this._TDocumentoEntregado = new EntitySet<TDocumentoEntregado>(new Action<TDocumentoEntregado>(this.attach_TDocumentoEntregado), new Action<TDocumentoEntregado>(this.detach_TDocumentoEntregado));
			this._TModalidadBeca = default(EntityRef<TModalidadBeca>);
			this._TDocumentoRequisito = default(EntityRef<TDocumentoRequisito>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRequisitos", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idRequisitos
		{
			get
			{
				return this._idRequisitos;
			}
			set
			{
				if ((this._idRequisitos != value))
				{
					this.OnidRequisitosChanging(value);
					this.SendPropertyChanging();
					this._idRequisitos = value;
					this.SendPropertyChanged("idRequisitos");
					this.OnidRequisitosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdModalidadBeca", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string IdModalidadBeca
		{
			get
			{
				return this._IdModalidadBeca;
			}
			set
			{
				if ((this._IdModalidadBeca != value))
				{
					if (this._TModalidadBeca.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdModalidadBecaChanging(value);
					this.SendPropertyChanging();
					this._IdModalidadBeca = value;
					this.SendPropertyChanged("IdModalidadBeca");
					this.OnIdModalidadBecaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDocumentoRequisito", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string idDocumentoRequisito
		{
			get
			{
				return this._idDocumentoRequisito;
			}
			set
			{
				if ((this._idDocumentoRequisito != value))
				{
					if (this._TDocumentoRequisito.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDocumentoRequisitoChanging(value);
					this.SendPropertyChanging();
					this._idDocumentoRequisito = value;
					this.SendPropertyChanged("idDocumentoRequisito");
					this.OnidDocumentoRequisitoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opcional", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string opcional
		{
			get
			{
				return this._opcional;
			}
			set
			{
				if ((this._opcional != value))
				{
					this.OnopcionalChanging(value);
					this.SendPropertyChanging();
					this._opcional = value;
					this.SendPropertyChanged("opcional");
					this.OnopcionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRequisitosBeca_TDocumentoEntregado", Storage="_TDocumentoEntregado", ThisKey="idRequisitos", OtherKey="idRequisitos")]
		public EntitySet<TDocumentoEntregado> TDocumentoEntregado
		{
			get
			{
				return this._TDocumentoEntregado;
			}
			set
			{
				this._TDocumentoEntregado.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TModalidadBeca_TRequisitosBeca", Storage="_TModalidadBeca", ThisKey="IdModalidadBeca", OtherKey="IdModalidadBeca", IsForeignKey=true)]
		public TModalidadBeca TModalidadBeca
		{
			get
			{
				return this._TModalidadBeca.Entity;
			}
			set
			{
				TModalidadBeca previousValue = this._TModalidadBeca.Entity;
				if (((previousValue != value) 
							|| (this._TModalidadBeca.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TModalidadBeca.Entity = null;
						previousValue.TRequisitosBeca.Remove(this);
					}
					this._TModalidadBeca.Entity = value;
					if ((value != null))
					{
						value.TRequisitosBeca.Add(this);
						this._IdModalidadBeca = value.IdModalidadBeca;
					}
					else
					{
						this._IdModalidadBeca = default(string);
					}
					this.SendPropertyChanged("TModalidadBeca");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TDocumentoRequisito_TRequisitosBeca", Storage="_TDocumentoRequisito", ThisKey="idDocumentoRequisito", OtherKey="idDocumentoRequisito", IsForeignKey=true)]
		public TDocumentoRequisito TDocumentoRequisito
		{
			get
			{
				return this._TDocumentoRequisito.Entity;
			}
			set
			{
				TDocumentoRequisito previousValue = this._TDocumentoRequisito.Entity;
				if (((previousValue != value) 
							|| (this._TDocumentoRequisito.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TDocumentoRequisito.Entity = null;
						previousValue.TRequisitosBeca.Remove(this);
					}
					this._TDocumentoRequisito.Entity = value;
					if ((value != null))
					{
						value.TRequisitosBeca.Add(this);
						this._idDocumentoRequisito = value.idDocumentoRequisito;
					}
					else
					{
						this._idDocumentoRequisito = default(string);
					}
					this.SendPropertyChanged("TDocumentoRequisito");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TDocumentoEntregado(TDocumentoEntregado entity)
		{
			this.SendPropertyChanging();
			entity.TRequisitosBeca = this;
		}
		
		private void detach_TDocumentoEntregado(TDocumentoEntregado entity)
		{
			this.SendPropertyChanging();
			entity.TRequisitosBeca = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TSolicitudBeca")]
	public partial class TSolicitudBeca : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdSolicitud;
		
		private System.DateTime _FecRegistro;
		
		private string _Estado;
		
		private string _IdUsuario;
		
		private string _IdModalidadBeca;
		
		private EntitySet<TDocumentoEntregado> _TDocumentoEntregado;
		
		private EntityRef<TUsuario> _TUsuario;
		
		private EntityRef<TModalidadBeca> _TModalidadBeca;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdSolicitudChanging(string value);
    partial void OnIdSolicitudChanged();
    partial void OnFecRegistroChanging(System.DateTime value);
    partial void OnFecRegistroChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnIdUsuarioChanging(string value);
    partial void OnIdUsuarioChanged();
    partial void OnIdModalidadBecaChanging(string value);
    partial void OnIdModalidadBecaChanged();
    #endregion
		
		public TSolicitudBeca()
		{
			this._TDocumentoEntregado = new EntitySet<TDocumentoEntregado>(new Action<TDocumentoEntregado>(this.attach_TDocumentoEntregado), new Action<TDocumentoEntregado>(this.detach_TDocumentoEntregado));
			this._TUsuario = default(EntityRef<TUsuario>);
			this._TModalidadBeca = default(EntityRef<TModalidadBeca>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSolicitud", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdSolicitud
		{
			get
			{
				return this._IdSolicitud;
			}
			set
			{
				if ((this._IdSolicitud != value))
				{
					this.OnIdSolicitudChanging(value);
					this.SendPropertyChanging();
					this._IdSolicitud = value;
					this.SendPropertyChanged("IdSolicitud");
					this.OnIdSolicitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FecRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime FecRegistro
		{
			get
			{
				return this._FecRegistro;
			}
			set
			{
				if ((this._FecRegistro != value))
				{
					this.OnFecRegistroChanging(value);
					this.SendPropertyChanging();
					this._FecRegistro = value;
					this.SendPropertyChanged("FecRegistro");
					this.OnFecRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					if (this._TUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdModalidadBeca", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string IdModalidadBeca
		{
			get
			{
				return this._IdModalidadBeca;
			}
			set
			{
				if ((this._IdModalidadBeca != value))
				{
					if (this._TModalidadBeca.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdModalidadBecaChanging(value);
					this.SendPropertyChanging();
					this._IdModalidadBeca = value;
					this.SendPropertyChanged("IdModalidadBeca");
					this.OnIdModalidadBecaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TSolicitudBeca_TDocumentoEntregado", Storage="_TDocumentoEntregado", ThisKey="IdSolicitud", OtherKey="IdSolicitud")]
		public EntitySet<TDocumentoEntregado> TDocumentoEntregado
		{
			get
			{
				return this._TDocumentoEntregado;
			}
			set
			{
				this._TDocumentoEntregado.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUsuario_TSolicitudBeca", Storage="_TUsuario", ThisKey="IdUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public TUsuario TUsuario
		{
			get
			{
				return this._TUsuario.Entity;
			}
			set
			{
				TUsuario previousValue = this._TUsuario.Entity;
				if (((previousValue != value) 
							|| (this._TUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TUsuario.Entity = null;
						previousValue.TSolicitudBeca.Remove(this);
					}
					this._TUsuario.Entity = value;
					if ((value != null))
					{
						value.TSolicitudBeca.Add(this);
						this._IdUsuario = value.IdUsuario;
					}
					else
					{
						this._IdUsuario = default(string);
					}
					this.SendPropertyChanged("TUsuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TModalidadBeca_TSolicitudBeca", Storage="_TModalidadBeca", ThisKey="IdModalidadBeca", OtherKey="IdModalidadBeca", IsForeignKey=true)]
		public TModalidadBeca TModalidadBeca
		{
			get
			{
				return this._TModalidadBeca.Entity;
			}
			set
			{
				TModalidadBeca previousValue = this._TModalidadBeca.Entity;
				if (((previousValue != value) 
							|| (this._TModalidadBeca.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TModalidadBeca.Entity = null;
						previousValue.TSolicitudBeca.Remove(this);
					}
					this._TModalidadBeca.Entity = value;
					if ((value != null))
					{
						value.TSolicitudBeca.Add(this);
						this._IdModalidadBeca = value.IdModalidadBeca;
					}
					else
					{
						this._IdModalidadBeca = default(string);
					}
					this.SendPropertyChanged("TModalidadBeca");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TDocumentoEntregado(TDocumentoEntregado entity)
		{
			this.SendPropertyChanging();
			entity.TSolicitudBeca = this;
		}
		
		private void detach_TDocumentoEntregado(TDocumentoEntregado entity)
		{
			this.SendPropertyChanging();
			entity.TSolicitudBeca = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TDocumentoEntregado")]
	public partial class TDocumentoEntregado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idDocumentoEntregado;
		
		private string _enlace;
		
		private string _idRequisitos;
		
		private string _IdSolicitud;
		
		private string _Estado;
		
		private EntitySet<TObservacion> _TObservacion;
		
		private EntityRef<TRequisitosBeca> _TRequisitosBeca;
		
		private EntityRef<TSolicitudBeca> _TSolicitudBeca;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDocumentoEntregadoChanging(string value);
    partial void OnidDocumentoEntregadoChanged();
    partial void OnenlaceChanging(string value);
    partial void OnenlaceChanged();
    partial void OnidRequisitosChanging(string value);
    partial void OnidRequisitosChanged();
    partial void OnIdSolicitudChanging(string value);
    partial void OnIdSolicitudChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    #endregion
		
		public TDocumentoEntregado()
		{
			this._TObservacion = new EntitySet<TObservacion>(new Action<TObservacion>(this.attach_TObservacion), new Action<TObservacion>(this.detach_TObservacion));
			this._TRequisitosBeca = default(EntityRef<TRequisitosBeca>);
			this._TSolicitudBeca = default(EntityRef<TSolicitudBeca>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDocumentoEntregado", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idDocumentoEntregado
		{
			get
			{
				return this._idDocumentoEntregado;
			}
			set
			{
				if ((this._idDocumentoEntregado != value))
				{
					this.OnidDocumentoEntregadoChanging(value);
					this.SendPropertyChanging();
					this._idDocumentoEntregado = value;
					this.SendPropertyChanged("idDocumentoEntregado");
					this.OnidDocumentoEntregadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enlace", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string enlace
		{
			get
			{
				return this._enlace;
			}
			set
			{
				if ((this._enlace != value))
				{
					this.OnenlaceChanging(value);
					this.SendPropertyChanging();
					this._enlace = value;
					this.SendPropertyChanged("enlace");
					this.OnenlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRequisitos", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string idRequisitos
		{
			get
			{
				return this._idRequisitos;
			}
			set
			{
				if ((this._idRequisitos != value))
				{
					if (this._TRequisitosBeca.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidRequisitosChanging(value);
					this.SendPropertyChanging();
					this._idRequisitos = value;
					this.SendPropertyChanged("idRequisitos");
					this.OnidRequisitosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSolicitud", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string IdSolicitud
		{
			get
			{
				return this._IdSolicitud;
			}
			set
			{
				if ((this._IdSolicitud != value))
				{
					if (this._TSolicitudBeca.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdSolicitudChanging(value);
					this.SendPropertyChanging();
					this._IdSolicitud = value;
					this.SendPropertyChanged("IdSolicitud");
					this.OnIdSolicitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TDocumentoEntregado_TObservacion", Storage="_TObservacion", ThisKey="idDocumentoEntregado", OtherKey="idDocumentoEntregado")]
		public EntitySet<TObservacion> TObservacion
		{
			get
			{
				return this._TObservacion;
			}
			set
			{
				this._TObservacion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRequisitosBeca_TDocumentoEntregado", Storage="_TRequisitosBeca", ThisKey="idRequisitos", OtherKey="idRequisitos", IsForeignKey=true)]
		public TRequisitosBeca TRequisitosBeca
		{
			get
			{
				return this._TRequisitosBeca.Entity;
			}
			set
			{
				TRequisitosBeca previousValue = this._TRequisitosBeca.Entity;
				if (((previousValue != value) 
							|| (this._TRequisitosBeca.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRequisitosBeca.Entity = null;
						previousValue.TDocumentoEntregado.Remove(this);
					}
					this._TRequisitosBeca.Entity = value;
					if ((value != null))
					{
						value.TDocumentoEntregado.Add(this);
						this._idRequisitos = value.idRequisitos;
					}
					else
					{
						this._idRequisitos = default(string);
					}
					this.SendPropertyChanged("TRequisitosBeca");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TSolicitudBeca_TDocumentoEntregado", Storage="_TSolicitudBeca", ThisKey="IdSolicitud", OtherKey="IdSolicitud", IsForeignKey=true)]
		public TSolicitudBeca TSolicitudBeca
		{
			get
			{
				return this._TSolicitudBeca.Entity;
			}
			set
			{
				TSolicitudBeca previousValue = this._TSolicitudBeca.Entity;
				if (((previousValue != value) 
							|| (this._TSolicitudBeca.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TSolicitudBeca.Entity = null;
						previousValue.TDocumentoEntregado.Remove(this);
					}
					this._TSolicitudBeca.Entity = value;
					if ((value != null))
					{
						value.TDocumentoEntregado.Add(this);
						this._IdSolicitud = value.IdSolicitud;
					}
					else
					{
						this._IdSolicitud = default(string);
					}
					this.SendPropertyChanged("TSolicitudBeca");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TObservacion(TObservacion entity)
		{
			this.SendPropertyChanging();
			entity.TDocumentoEntregado = this;
		}
		
		private void detach_TObservacion(TObservacion entity)
		{
			this.SendPropertyChanging();
			entity.TDocumentoEntregado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TDocumentoRequisito")]
	public partial class TDocumentoRequisito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idDocumentoRequisito;
		
		private string _nombre;
		
		private string _enlaceFormato;
		
		private EntitySet<TRequisitosBeca> _TRequisitosBeca;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDocumentoRequisitoChanging(string value);
    partial void OnidDocumentoRequisitoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnenlaceFormatoChanging(string value);
    partial void OnenlaceFormatoChanged();
    #endregion
		
		public TDocumentoRequisito()
		{
			this._TRequisitosBeca = new EntitySet<TRequisitosBeca>(new Action<TRequisitosBeca>(this.attach_TRequisitosBeca), new Action<TRequisitosBeca>(this.detach_TRequisitosBeca));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDocumentoRequisito", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string idDocumentoRequisito
		{
			get
			{
				return this._idDocumentoRequisito;
			}
			set
			{
				if ((this._idDocumentoRequisito != value))
				{
					this.OnidDocumentoRequisitoChanging(value);
					this.SendPropertyChanging();
					this._idDocumentoRequisito = value;
					this.SendPropertyChanged("idDocumentoRequisito");
					this.OnidDocumentoRequisitoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enlaceFormato", DbType="VarChar(250)")]
		public string enlaceFormato
		{
			get
			{
				return this._enlaceFormato;
			}
			set
			{
				if ((this._enlaceFormato != value))
				{
					this.OnenlaceFormatoChanging(value);
					this.SendPropertyChanging();
					this._enlaceFormato = value;
					this.SendPropertyChanged("enlaceFormato");
					this.OnenlaceFormatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TDocumentoRequisito_TRequisitosBeca", Storage="_TRequisitosBeca", ThisKey="idDocumentoRequisito", OtherKey="idDocumentoRequisito")]
		public EntitySet<TRequisitosBeca> TRequisitosBeca
		{
			get
			{
				return this._TRequisitosBeca;
			}
			set
			{
				this._TRequisitosBeca.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TRequisitosBeca(TRequisitosBeca entity)
		{
			this.SendPropertyChanging();
			entity.TDocumentoRequisito = this;
		}
		
		private void detach_TRequisitosBeca(TRequisitosBeca entity)
		{
			this.SendPropertyChanging();
			entity.TDocumentoRequisito = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vistaSolicitudesPorModalidad")]
	public partial class vistaSolicitudesPorModalidad
	{
		
		private string _Nombre;
		
		private System.Nullable<int> _Cantidad;
		
		public vistaSolicitudesPorModalidad()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(55) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vistaSolicitudesPorEscuela")]
	public partial class vistaSolicitudesPorEscuela
	{
		
		private string _Nombre;
		
		private System.Nullable<int> _Cantidad;
		
		public vistaSolicitudesPorEscuela()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vistaSolicitudesPorEstado")]
	public partial class vistaSolicitudesPorEstado
	{
		
		private string _Nombre;
		
		private System.Nullable<int> _Cantidad;
		
		public vistaSolicitudesPorEstado()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vistaSolicitudesAprobadasPorEscuela")]
	public partial class vistaSolicitudesAprobadasPorEscuela
	{
		
		private string _Nombre;
		
		private System.Nullable<int> _Cantidad;
		
		public vistaSolicitudesAprobadasPorEscuela()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vistaSolicitudesAprobadasPorModalidad")]
	public partial class vistaSolicitudesAprobadasPorModalidad
	{
		
		private string _Nombre;
		
		private System.Nullable<int> _Cantidad;
		
		public vistaSolicitudesAprobadasPorModalidad()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(55) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	public partial class spLoginUsuarioResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spLoginUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spAgregarEncargadoResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spAgregarEncargadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(34) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spModificarUsuarioResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spModificarUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spAgregarImagenResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spAgregarImagenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spListarRequisitoporModalidadResult
	{
		
		private string _idDocumentoRequisito;
		
		private string _nombre;
		
		private string _opcional;
		
		public spListarRequisitoporModalidadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDocumentoRequisito", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string idDocumentoRequisito
		{
			get
			{
				return this._idDocumentoRequisito;
			}
			set
			{
				if ((this._idDocumentoRequisito != value))
				{
					this._idDocumentoRequisito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opcional", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string opcional
		{
			get
			{
				return this._opcional;
			}
			set
			{
				if ((this._opcional != value))
				{
					this._opcional = value;
				}
			}
		}
	}
	
	public partial class spAgregarDocumentoEntregadoResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spAgregarDocumentoEntregadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(33) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spListarDocumentosPorSolicitudResult
	{
		
		private string _idDocumentoRequisito;
		
		private string _nombre;
		
		public spListarDocumentosPorSolicitudResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDocumentoRequisito", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string idDocumentoRequisito
		{
			get
			{
				return this._idDocumentoRequisito;
			}
			set
			{
				if ((this._idDocumentoRequisito != value))
				{
					this._idDocumentoRequisito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
	}
	
	public partial class spAgregarSolicitudResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spAgregarSolicitudResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="Char(5)")]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spAgregarObservacionResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spAgregarObservacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class spListarDocumentosPorUsuarioResult
	{
		
		private string _idDocumentoRequisito;
		
		private string _nombre;
		
		public spListarDocumentosPorUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDocumentoRequisito", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string idDocumentoRequisito
		{
			get
			{
				return this._idDocumentoRequisito;
			}
			set
			{
				if ((this._idDocumentoRequisito != value))
				{
					this._idDocumentoRequisito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
	}
	
	public partial class spAgregarEstudianteResult
	{
		
		private int _CodError;
		
		private string _Mensaje;
		
		public spAgregarEstudianteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodError", DbType="Int NOT NULL")]
		public int CodError
		{
			get
			{
				return this._CodError;
			}
			set
			{
				if ((this._CodError != value))
				{
					this._CodError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(34) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
